//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Android_Transfer_Protocol.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Android_Transfer_Protocol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ADB 丢失 的本地化字符串。
        /// </summary>
        public static string AdbLose {
            get {
                return ResourceManager.GetString("AdbLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备 的本地化字符串。
        /// </summary>
        public static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android Transfer Protocol 的本地化字符串。
        /// </summary>
        public static string ATP {
            get {
                return ResourceManager.GetString("ATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权 的本地化字符串。
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 块设备 的本地化字符串。
        /// </summary>
        public static string BLOCK {
            get {
                return ResourceManager.GetString("BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退(Alt + ←) 的本地化字符串。
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(Ctrl + C) 的本地化字符串。
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切(Ctrl + X) 的本地化字符串。
        /// </summary>
        public static string Button_Cut {
            get {
                return ResourceManager.GetString("Button_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除(Delete) 的本地化字符串。
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进(Alt + →) 的本地化字符串。
        /// </summary>
        public static string Button_Forward {
            get {
                return ResourceManager.GetString("Button_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(Ctrl + V) 的本地化字符串。
        /// </summary>
        public static string Button_Paste {
            get {
                return ResourceManager.GetString("Button_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新(F5) 的本地化字符串。
        /// </summary>
        public static string Button_Reflush {
            get {
                return ResourceManager.GetString("Button_Reflush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名(F2) 的本地化字符串。
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一级(Alt + ↑) 的本地化字符串。
        /// </summary>
        public static string Button_Upper {
            get {
                return ResourceManager.GetString("Button_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符设备 的本地化字符串。
        /// </summary>
        public static string CHAR {
            get {
                return ResourceManager.GetString("CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        public static string CONNECTED {
            get {
                return ResourceManager.GetString("CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接丢失或被拒绝 的本地化字符串。
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在复制 的本地化字符串。
        /// </summary>
        public static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在新建文件(夹) 的本地化字符串。
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销授权 的本地化字符串。
        /// </summary>
        public static string Deauthorization {
            get {
                return ResourceManager.GetString("Deauthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在删除 的本地化字符串。
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号 的本地化字符串。
        /// </summary>
        public static string DeviceNum {
            get {
                return ResourceManager.GetString("DeviceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string DIR {
            get {
                return ResourceManager.GetString("DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接 的本地化字符串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载 的本地化字符串。
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本 的本地化字符串。
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试提权 的本地化字符串。
        /// </summary>
        public static string Elevation {
            get {
                return ResourceManager.GetString("Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在同名文件(夹) 的本地化字符串。
        /// </summary>
        public static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制刷新 的本地化字符串。
        /// </summary>
        public static string ForcedReflush {
            get {
                return ResourceManager.GetString("ForcedReflush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏工具栏 的本地化字符串。
        /// </summary>
        public static string HideTools {
            get {
                return ResourceManager.GetString("HideTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效路径 的本地化字符串。
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址(_A): 的本地化字符串。
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口(可选)(_P): 的本地化字符串。
        /// </summary>
        public static string Label_Port {
            get {
                return ResourceManager.GetString("Label_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接文件 的本地化字符串。
        /// </summary>
        public static string LINK_FILE {
            get {
                return ResourceManager.GetString("LINK_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_AddDevice {
            get {
                return ResourceManager.GetString("Menu_AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_Authorization {
            get {
                return ResourceManager.GetString("Menu_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退(_B) 的本地化字符串。
        /// </summary>
        public static string Menu_Back {
            get {
                return ResourceManager.GetString("Menu_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览(_B) 的本地化字符串。
        /// </summary>
        public static string Menu_Browse {
            get {
                return ResourceManager.GetString("Menu_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览(_B) 的本地化字符串。
        /// </summary>
        public static string Menu_BrowseTools {
            get {
                return ResourceManager.GetString("Menu_BrowseTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选中 的本地化字符串。
        /// </summary>
        public static string Menu_CancelSelected {
            get {
                return ResourceManager.GetString("Menu_CancelSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新(_C) 的本地化字符串。
        /// </summary>
        public static string Menu_CheckUpdate {
            get {
                return ResourceManager.GetString("Menu_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接(_C) 的本地化字符串。
        /// </summary>
        public static string Menu_Connect {
            get {
                return ResourceManager.GetString("Menu_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制(_C) 的本地化字符串。
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切(_T) 的本地化字符串。
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销授权(_D) 的本地化字符串。
        /// </summary>
        public static string Menu_Deauthorization {
            get {
                return ResourceManager.GetString("Menu_Deauthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除(_D) 的本地化字符串。
        /// </summary>
        public static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备(_D) 的本地化字符串。
        /// </summary>
        public static string Menu_Device {
            get {
                return ResourceManager.GetString("Menu_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接(_D) 的本地化字符串。
        /// </summary>
        public static string Menu_Disconnect {
            get {
                return ResourceManager.GetString("Menu_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载(_L) 的本地化字符串。
        /// </summary>
        public static string Menu_Download {
            get {
                return ResourceManager.GetString("Menu_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本(_E) 的本地化字符串。
        /// </summary>
        public static string Menu_Duplicate {
            get {
                return ResourceManager.GetString("Menu_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(_E) 的本地化字符串。
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑(_E) 的本地化字符串。
        /// </summary>
        public static string Menu_EditTools {
            get {
                return ResourceManager.GetString("Menu_EditTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试提权(_E) 的本地化字符串。
        /// </summary>
        public static string Menu_Elevation {
            get {
                return ResourceManager.GetString("Menu_Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出(_X) 的本地化字符串。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制刷新(_F) 的本地化字符串。
        /// </summary>
        public static string Menu_ForcedReflush {
            get {
                return ResourceManager.GetString("Menu_ForcedReflush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进(_F) 的本地化字符串。
        /// </summary>
        public static string Menu_Forward {
            get {
                return ResourceManager.GetString("Menu_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(_H) 的本地化字符串。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如何使用(_U) 的本地化字符串。
        /// </summary>
        public static string Menu_HowToUse {
            get {
                return ResourceManager.GetString("Menu_HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建(_W) 的本地化字符串。
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接(_O) 的本地化字符串。
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴(_V) 的本地化字符串。
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新(_R) 的本地化字符串。
        /// </summary>
        public static string Menu_Reflush {
            get {
                return ResourceManager.GetString("Menu_Reflush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名(_R) 的本地化字符串。
        /// </summary>
        public static string Menu_Rename {
            get {
                return ResourceManager.GetString("Menu_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_SelectAll {
            get {
                return ResourceManager.GetString("Menu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务列表(_T) 的本地化字符串。
        /// </summary>
        public static string Menu_TaskList {
            get {
                return ResourceManager.GetString("Menu_TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具栏(_T) 的本地化字符串。
        /// </summary>
        public static string Menu_Toolbar {
            get {
                return ResourceManager.GetString("Menu_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件传输(_T) 的本地化字符串。
        /// </summary>
        public static string Menu_TransmissionTools {
            get {
                return ResourceManager.GetString("Menu_TransmissionTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传(_U) 的本地化字符串。
        /// </summary>
        public static string Menu_Upload {
            get {
                return ResourceManager.GetString("Menu_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一级(_U) 的本地化字符串。
        /// </summary>
        public static string Menu_Upper {
            get {
                return ResourceManager.GetString("Menu_Upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图(_V) 的本地化字符串。
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在地址处填写您的设备的主机名或 IP 地址, 端口默认为 5555。 的本地化字符串。
        /// </summary>
        public static string Message_AddDeviceTip {
            get {
                return ResourceManager.GetString("Message_AddDeviceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此设备不允许通过这种方式断开连接 的本地化字符串。
        /// </summary>
        public static string Message_CanNoDisconnect {
            get {
                return ResourceManager.GetString("Message_CanNoDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否覆盖文件或合并文件夹 的本地化字符串。
        /// </summary>
        public static string Message_CoverFile {
            get {
                return ResourceManager.GetString("Message_CoverFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要永久地删除这些文件(夹)吗? 的本地化字符串。
        /// </summary>
        public static string Message_DeleteConfirm {
            get {
                return ResourceManager.GetString("Message_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要断开与该设备的连接吗? 的本地化字符串。
        /// </summary>
        public static string Message_DisconnectConfirm {
            get {
                return ResourceManager.GetString("Message_DisconnectConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要保存文件的路径: 的本地化字符串。
        /// </summary>
        public static string Message_DownloadPath {
            get {
                return ResourceManager.GetString("Message_DownloadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有任务尚未完成, 关闭该窗口将中断任务, 确定要继续退出吗? 的本地化字符串。
        /// </summary>
        public static string Message_ExitConfirm {
            get {
                return ResourceManager.GetString("Message_ExitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入地址! 的本地化字符串。
        /// </summary>
        public static string Message_NoAddressTip {
            get {
                return ResourceManager.GetString("Message_NoAddressTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string Message_OperationFailed {
            get {
                return ResourceManager.GetString("Message_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要停止所有操作吗? 的本地化字符串。
        /// </summary>
        public static string Message_StopTip {
            get {
                return ResourceManager.GetString("Message_StopTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备型号 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在移动 的本地化字符串。
        /// </summary>
        public static string Moving {
            get {
                return ResourceManager.GetString("Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        public static string NewDir {
            get {
                return ResourceManager.GetString("NewDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件 的本地化字符串。
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(夹)不存在 的本地化字符串。
        /// </summary>
        public static string NoSuchFile {
            get {
                return ResourceManager.GetString("NoSuchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string OFFLINE {
            get {
                return ResourceManager.GetString("OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开该文件或路径 的本地化字符串。
        /// </summary>
        public static string PathError {
            get {
                return ResourceManager.GetString("PathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限不足 的本地化字符串。
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管道文件 的本地化字符串。
        /// </summary>
        public static string PIPE {
            get {
                return ResourceManager.GetString("PIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Pression {
            get {
                return ResourceManager.GetString("Pression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在读取 的本地化字符串。
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读 的本地化字符串。
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复模式 的本地化字符串。
        /// </summary>
        public static string RECOVERY {
            get {
                return ResourceManager.GetString("RECOVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Reflush {
            get {
                return ResourceManager.GetString("Reflush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在刷新 的本地化字符串。
        /// </summary>
        public static string Reflushing {
            get {
                return ResourceManager.GetString("Reflushing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在重命名 的本地化字符串。
        /// </summary>
        public static string Renaming {
            get {
                return ResourceManager.GetString("Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已获 root 授权 的本地化字符串。
        /// </summary>
        public static string Rooted {
            get {
                return ResourceManager.GetString("Rooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择设备 的本地化字符串。
        /// </summary>
        public static string Select_Devices {
            get {
                return ResourceManager.GetString("Select_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选 的本地化字符串。
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 严重错误 的本地化字符串。
        /// </summary>
        public static string SeriousError {
            get {
                return ResourceManager.GetString("SeriousError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套接口文件 的本地化字符串。
        /// </summary>
        public static string SOCKET {
            get {
                return ResourceManager.GetString("SOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总计 的本地化字符串。
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未授权 的本地化字符串。
        /// </summary>
        public static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在上传 的本地化字符串。
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名 的本地化字符串。
        /// </summary>
        public static string UsbSerialNum {
            get {
                return ResourceManager.GetString("UsbSerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
