//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Android_Transfer_Protocol.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Android_Transfer_Protocol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ADB 丢失 的本地化字符串。
        /// </summary>
        public static string AdbLose {
            get {
                return ResourceManager.GetString("AdbLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备 的本地化字符串。
        /// </summary>
        public static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android Transfer Protocol 的本地化字符串。
        /// </summary>
        public static string ATP {
            get {
                return ResourceManager.GetString("ATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 块设备 的本地化字符串。
        /// </summary>
        public static string BLOCK {
            get {
                return ResourceManager.GetString("BLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符设备 的本地化字符串。
        /// </summary>
        public static string CHAR {
            get {
                return ResourceManager.GetString("CHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        public static string CONNECTED {
            get {
                return ResourceManager.GetString("CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败或丢失 的本地化字符串。
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号 的本地化字符串。
        /// </summary>
        public static string DeviceNum {
            get {
                return ResourceManager.GetString("DeviceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string DIR {
            get {
                return ResourceManager.GetString("DIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string FILE {
            get {
                return ResourceManager.GetString("FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在同名文件(夹) 的本地化字符串。
        /// </summary>
        public static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组 的本地化字符串。
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址(_A): 的本地化字符串。
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口(可选)(_P): 的本地化字符串。
        /// </summary>
        public static string Label_Port {
            get {
                return ResourceManager.GetString("Label_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接文件 的本地化字符串。
        /// </summary>
        public static string LINK_FILE {
            get {
                return ResourceManager.GetString("LINK_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备(_A) 的本地化字符串。
        /// </summary>
        public static string Menu_AddDevice {
            get {
                return ResourceManager.GetString("Menu_AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新(_C) 的本地化字符串。
        /// </summary>
        public static string Menu_CheckUpdate {
            get {
                return ResourceManager.GetString("Menu_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备(_D) 的本地化字符串。
        /// </summary>
        public static string Menu_Device {
            get {
                return ResourceManager.GetString("Menu_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接(_D) 的本地化字符串。
        /// </summary>
        public static string Menu_Disconnect {
            get {
                return ResourceManager.GetString("Menu_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制刷新(_F) 的本地化字符串。
        /// </summary>
        public static string Menu_ForcedReflush {
            get {
                return ResourceManager.GetString("Menu_ForcedReflush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助(_H) 的本地化字符串。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如何使用(_U) 的本地化字符串。
        /// </summary>
        public static string Menu_HowToUse {
            get {
                return ResourceManager.GetString("Menu_HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新(_R) 的本地化字符串。
        /// </summary>
        public static string Menu_Reflush {
            get {
                return ResourceManager.GetString("Menu_Reflush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在地址处填写您的设备的主机名或 IP 地址, 端口默认为 5555。 的本地化字符串。
        /// </summary>
        public static string Message_AddDeviceTip {
            get {
                return ResourceManager.GetString("Message_AddDeviceTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此设备不允许通过该发生断开连接 的本地化字符串。
        /// </summary>
        public static string Message_CanNoDisconnect {
            get {
                return ResourceManager.GetString("Message_CanNoDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要永久地删除所选文件(夹)吗? 的本地化字符串。
        /// </summary>
        public static string Message_DeleteConfirm {
            get {
                return ResourceManager.GetString("Message_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入地址! 的本地化字符串。
        /// </summary>
        public static string Message_NoAddressTip {
            get {
                return ResourceManager.GetString("Message_NoAddressTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备型号 的本地化字符串。
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件夹 的本地化字符串。
        /// </summary>
        public static string NewDir {
            get {
                return ResourceManager.GetString("NewDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建文件 的本地化字符串。
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件(夹)不存在 的本地化字符串。
        /// </summary>
        public static string NoSuchFile {
            get {
                return ResourceManager.GetString("NoSuchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string OFFLINE {
            get {
                return ResourceManager.GetString("OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开该文件或路径 的本地化字符串。
        /// </summary>
        public static string PathError {
            get {
                return ResourceManager.GetString("PathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限不足 的本地化字符串。
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管道文件 的本地化字符串。
        /// </summary>
        public static string PIPE {
            get {
                return ResourceManager.GetString("PIPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Pression {
            get {
                return ResourceManager.GetString("Pression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读 的本地化字符串。
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择设备 的本地化字符串。
        /// </summary>
        public static string Select_Devices {
            get {
                return ResourceManager.GetString("Select_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 严重错误 的本地化字符串。
        /// </summary>
        public static string SeriousError {
            get {
                return ResourceManager.GetString("SeriousError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套接口文件 的本地化字符串。
        /// </summary>
        public static string SOCKET {
            get {
                return ResourceManager.GetString("SOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未授权 的本地化字符串。
        /// </summary>
        public static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名 的本地化字符串。
        /// </summary>
        public static string UsbSerialNum {
            get {
                return ResourceManager.GetString("UsbSerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
